language: node_js
sudo: false
node_js:
  - 8

addons:
  apt:
    update: true
    packages:
      - rpm
      - fakeroot

install:
  - npm install

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run package
  - npm test

os:
  - linux
  - osx

before_deploy:
  - npm run make

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
    node: 8
