language: node_js
sudo: false
node_js:
  - 8

addons:
  apt:
    update: true
    packages:
      - rpm
      - fakeroot

install:
  - npm install

cache:
  directories:
    - node_modules
    - zips

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start          ; fi
  - sleep 3 # give xvfb some time to start

script:
  - npm run package
  - npm test

os:
  - linux
  - osx

before_deploy:
  - npm run make

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
    node: 8
