language: node_js
sudo: false
node_js:
  - 8

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  apt:
    update: true
    packages:
      - rpm
      - fakeroot

install:
  - npm install

cache:
  directories:
    - node_modules
    - zips

services:
  - xvfb

script:
  - npm run package
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm test; fi

os:
  - linux
  - osx

before_deploy:
  - npm run make

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
    node: 8
