language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install fakeroot

install:
  - npm install

script:
  - npm test
  - npm run make

os:
  - linux
  - osx

deploy:
  provider: releases
  api_key: $TOKEN
  file: "out/make/*"
  skip_cleanup: true
  on:
    tags: true
