language: node_js
sudo: false
node_js:
  - 8

branches:
  only:
    - master
    - develop

addons:
  apt:
    update: true
    packages:
      - rpm
      - fakeroot

install:
  - npm install

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

script:
  - npm test

os:
  - linux
  - osx

before_deploy:
  - npm run make

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
    node: 8
