language: node_js
sudo: false
node_js:
  - 8

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx

addons:
  apt:
    update: true
    packages:
      - rpm
      - fakeroot

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run make

os:
  - linux
  - osx

deploy:
  provider: releases
  api_key: $TOKEN
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
    node: 8
