name: CI
on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn build:linux
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-linux
          path: dist/*-linux.*